### ISSUE TITLE
java.lang.RuntimeException: getParameters failed on Nexus 7 

### ISSUE THREAD

**Issue by learnNcode** [commonsguy/cwac-camera#252]
```xml
java.lang.RuntimeException: getParameters failed (empty parameters)
at android.hardware.Camera.native_getParameters(Native Method)
at android.hardware.Camera.getParameters(Camera.java:1663)
at com.commonsware.cwac.camera.i.onOrientationChanged(SourceFile:657)
at android.view.OrientationEventListener$SensorEventListenerImpl.onSensorChanged(OrientationEventListener.java:143)	
at android.hardware.SystemSensorManager$SensorEventQueue.dispatchSensorEvent(SystemSensorManager.java:418)
at android.os.MessageQueue.nativePollOnce(Native Method)
at android.os.MessageQueue.next(MessageQueue.java:138)
at android.os.Looper.loop(Looper.java:123)
at android.app.ActivityThread.main(ActivityThread.java:5001)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:515)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)	
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)	
at dalvik.system.NativeStart.main(Native Method)
```

**Comment by commonsguy** [comment]
@learnNcode There are multiple Nexus 7 devices. I need to know which specific `Build.PRODUCT` this is, what version of Android it runs, and what you did in the demo apps to generate this stack trace.

**Comment by fertwo** [comment]
I have the same issue on ASUS Nexus 7/ME370T (tablet)

When I try to launch the camera in landscape mode the application crashes .

Class CameraView: 

 @Override
    public void onOrientationChanged(int orientation) {
      if (camera != null && orientation != ORIENTATION_UNKNOWN) {
        int newOutputOrientation=getCameraPictureRotation(orientation);

        if (newOutputOrientation != outputOrientation) {
          outputOrientation=newOutputOrientation;

          Camera.Parameters params=camera.getParameters(); //crashes here

          params.setRotation(outputOrientation);
...

The stacktrace of the exception is the same.

Any ideas?

Tnx

**Comment by commonsguy** [comment]
@fertwo I need the complete steps to reproduce this problem with the demo app, or with some app whose source you provide.

**Comment by grote** [comment]
This might be related: http://stackoverflow.com/questions/14941625/correct-handling-of-exception-getparameters-failed-empty-parameters
