### ISSUE TITLE
OOM in ImageCleanupTask

### ISSUE THREAD

**Issue by Tan-Tshunglee** [commonsguy/cwac-camera#264]
AndroidRuntime﹕ FATAL EXCEPTION: Thread-981
      java.lang.OutOfMemoryError
            at android.graphics.Bitmap.nativeCreate(Native Method)
            at android.graphics.Bitmap.createBitmap(Bitmap.java:810)
            at android.graphics.Bitmap.createBitmap(Bitmap.java:787)
            at android.graphics.Bitmap.createBitmap(Bitmap.java:719)
            at com.commonsware.cwac.camera.ImageCleanupTask.run(ImageCleanupTask.java:121)

**Comment by commonsguy** [comment]
You are out of memory. There is nothing that I can do about that. You may wish to read [the documentation](https://github.com/commonsguy/cwac-camera#fixing-up-images-and-your-heap) for things that you can do to control this behavior.
