### ISSUE TITLE
Auto Focus is not working with Camera Fragment

### ISSUE THREAD

**Issue by FelipeRRM** [commonsguy/cwac-camera#266]
I'm getting this error:

```javascript
 java.lang.RuntimeException: autoFocus failed
            at android.hardware.Camera.native_autoFocus(Native Method)
            at android.hardware.Camera.autoFocus(Camera.java:1120)
            at com.getset.mosaic.main.camera.src.com.commonsware.cwac.camera.CameraView.autoFocus(CameraView.java:397)
            at com.getset.mosaic.main.camera.src.com.commonsware.cwac.camera.CameraFragment.autoFocus(CameraFragment.java:224)
            at com.getset.mosaic.main.DialogFragmentCamera$6.onTouch(DialogFragmentCamera.java:194)
```

When I try to use the auto focus on the camera fragment. The preview is already working and I can take pictures just fine, but as soon as I click the view (which invokes auto focus) I get this error.

I'm putting the CameraFragment inside another Fragment (a DialogFragment), using this method:
```javascript
private void setUpCameraView(View parentView) {
        frameLayout = (FrameLayout) parentView.findViewById(R.id.mainLayout);
        frameLayout.post(new Runnable() {
            @Override
            public void run() {
                ViewGroup.LayoutParams params = frameLayout.getLayoutParams();
                params.height = frameLayout.getWidth();
                frameLayout.setLayoutParams(params);
                frameLayout.postInvalidate();
            }
        });

        cameraFragmentView = new CameraFragmentView();
        cameraHost = new MeuCameraHost(getActivity(),this);
        cameraFragmentView.setHost(cameraHost);
        getChildFragmentManager().beginTransaction().add(R.id.mainLayout,cameraFragmentView).commit();

        frameLayout.setOnTouchListener(new View.OnTouchListener() {
            @Override
            public boolean onTouch(View v, MotionEvent event) {
                if(cameraFragmentView.isAutoFocusAvailable()){
                    cameraFragmentView.autoFocus();
                }
                return true;
            }
        });
    }
```
parentView is just the view I inflated on the onCreateView, and call this setUpCameraView() just after it.
cameraFragmentView overrides CameraFragment (but I actually did not change anything)
and MeuCameraHost overrides SimpleCameraHost.

Any help is appreciated!

**Comment by commonsguy** [comment]
If you can reproduce the problem with the demo app, let me know exactly what hardware you are using and the exact steps to reproduce the problem.

If you cannot reproduce the problem with the demo app, but you can publish some project that itself can reproduce the problem, publish that project, link to it from here, and let me know exactly what hardware you are using and the exact steps tor reproduce the problem.
